name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Docker
      run: sudo apt install runc containerd docker.io
    - name: Build the Docker image
      run: |
        docker build -t logger .
        docker images
        docker inspect logger
        cat hello_world_application/hello_world.cpp
